version: '3.8'


x-shared_environment: &shared_environment
  IY_RMQ_HOST: iy-rabbitmq
  IY_RMQ_PORT: 5672
  IY_RABBITMQ_HOST: iy-rabbitmq
  IY_RABBITMQ_PORT: 5672
  IY_MONGO_HOST: iy-mongo
  IY_MONGO_PORT: 27017
  IY_MONGO_DB: iy
  IY_REDIS_HOST: iy-redis
  IY_REDIS_PORT: 6379
  IY_BULL_USER: ${IY_BULL_USER}
  IY_BULL_PWD: ${IY_BULL_PWD}
  
  IY_GOOGLE_CLIENT_ID: ${IY_GOOGLE_CLIENT_ID}
  IY_GOOGLE_CLIENT_SECRET: ${IY_GOOGLE_CLIENT_SECRET}
  IY_GOOGLE_REDIRECT_URI: http://${IY_BE_HOST}:${IY_BE_PORT}/v1/auth/google_redirect
  IY_FACEBOOK_APP_ID: ${IY_FACEBOOK_APP_ID}
  IY_FACEBOOK_APP_SECRET: ${IY_FACEBOOK_APP_SECRET}
  IY_FACEBOOK_REDIRECT_URI: http://${IY_BE_HOST}:${IY_BE_PORT}/v1/auth/facebook_redirect
  IY_FRONTEND_REDIRECT_LOGIN: ${IY_FRONTEND_REDIRECT_LOGIN}
  IY_FRONTEND_REDIRECT_LOGIN_FAILED: ${IY_FRONTEND_REDIRECT_LOGIN_FAILED}
  IY_JWT_REFRESH_SECRET: ${IY_JWT_REFRESH_SECRET}
  IY_JWT_REFRESH_EXPIRED: ${IY_JWT_REFRESH_EXPIRED}
  IY_JWT_ACCESS_SECRET: ${IY_JWT_ACCESS_SECRET}
  IY_JWT_ACCESS_EXPIRED: ${IY_JWT_ACCESS_EXPIRED}
  
  IY_MAIL_SERVICE: ${IY_MAIL_SERVICE}
  IY_MAIL_USER: ${IY_MAIL_USER}
  IY_MAIL_PASS: ${IY_MAIL_PASS}
  
services:
  iy-gateway:
    image: iy-dev
    build:
      dockerfile: ./dev.node18.Dockerfile
      context: .
      args:
        - gUser=${IY_H_NAME}
        - gId=${IY_H_ID}
    environment:
      <<: *shared_environment
    ports:
      - "${IY_BE_PORT}:3000"
    volumes:
      - ../apps/investiway:/data/apps
    
  iy-rabbitmq:
    image: rabbitmq:3.9.27-alpine
    environment:
      <<: *shared_environment
    command: sh -c "rm -rf /etc/rabbimq/conf.d && rabbitmq-plugins enable rabbitmq_management && rabbitmq-server"
    ports:
      - "15672:15672"
    volumes:
      - ../conf/rabbitmq-dev:/etc/rabbitmq/
        
  iy-redis:
    image: redis:7.0.7-alpine3.17
    environment:
      <<: *shared_environment
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../conf/redis.dev.conf:/usr/local/etc/redis/redis.conf
      - ../data/redis:/data
        
  iy-mongo:
    image: mongo:6.0.3
    command: mongod --quiet --logpath /dev/null
    environment:
      <<: *shared_environment
    ports:
      - "27017:27017"
    volumes:
      - ../conf/mongod.dev.conf:/etc/mongodb.conf
      - ../data/mongo/log:/var/log/mongodb/
      - ../data/mongo/data:/data/db