name: Deploy Render
on:
  push:
    tags:        
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        test:
          [
            investiway
          ]
    steps:
      - name: Webhook Render
        uses: distributhor/workflow-webhook
        with:
          url: "https://api.render.com/deploy/${{ secrets.RENDER_SERVICE }}/${{ secrets.RENDER_HOOK }}"