name: deploy
on:
  workflow_run:
    workflows: ["Continuous Integration Testing"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        test:
          [
            investiway
          ]
    if: github.event.workflow_run.event == 'released'
    steps:
      - name: Pull
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Install & build
        run: |
          cd apps/investiway
          yarn
          yarn build
      - name: Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-args: '--prod'
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./apps/investiway/dist